WebAssembly/tool-conventions

BasicCABI.md, ItaniumLikeC++ABI.md, README.md
- Wrap at 80 cols
- Remove unicode quote chars
- Add title to README.md
- Use links when referencing other .md files
=> Markdown formatting improvements

Linking.md
Because we want to be able to write C++ global addresses into the data section,
we can't count on using a get_global to read the value of an imported global to
get the C++ global address. In view of that, and the fact that it's also simpler
to write addresses directly into the code section than use an actual get_global,
drop the get_globals altogether. This results in several changes to the
relocations.
And, add an addend field to C++ global address relocations. I think this ends
up making sense because it makes sense for the addend to be signed, but some of
the relocations apply to fields which are unsigned, so storing the addend in them
is awkward.
LLVM isn't quite finished implementing the stack pointer part of this, and as I wrote this up, I also realized that it's missing support for …
=> Describe the relocations that LLVM is currently using.

ItaniumLikeC++ABI.md
The old link returns 404 error.
=> Fix broken link

Linking.md
This changes the "linking" section to be made up of
subsection in the same way as the "names" section.
This allows unknown subsections to be skipped over.
I've implemented this new behaviour in wabt and
also in the llvm reader and writer code:
https://github.com/WebAssembly/wabt/pull/483
https://reviews.llvm.org/D34019
=> Define symbol info linking section

Linking.md
Add new linking metadata types for memory and tables.
Also, remove WASM_DATA_SIZE, which is redundant with the "minimum" field
of the linear memory description.
This documents the changes proposed in LLVM patch [D40875](https://reviews.llvm.org/D40875).
I'm not attached to most of the particular details here; my main interest is in switching to imports for memory and tables.
=> Add a comment about the motivation for WASM_DATA_SIZE.

Linking.md
As discussed in
https://github.com/WebAssembly/tool-conventions/pull/26
this removes WASM_STACK_POINTER.
=> Remove WASM_STACK_POINTER.

Linking.md
This is the documentation for the corresponding change in https://reviews.llvm.org/D40844, to be documented as and when that format is accepted.
See the discussion in LLVM bugzilla and Phabricator for information on COMDAT.
=> Add COMDAT linking data encoding

Linking.md
This implements the spec changes discussed in issue https://github.com/WebAssembly/tool-conventions/issues/38.
Changes:
* Gets rid of globals as a way of modelling data
* Add globals for real Wasm globals such as `__stack_pointer`
* Specifies ways that relocation processing can/must fail
* Specifies the Wasm object file symbol table
=> Create an explicit symbol table

Linking.md
They are no longer needed to used in llvm/lld now that we
have segment info and symbol table metadata.
=> Remove DATA_SIZE and DATA_ALIGNMENT

Linking.md
this is inline with the offical spec where value types are specified as single bytes and
not LEBs.
Also, use lower case when naming elements of the binary structure.
=> Use uint8 consistently for enum types

DynamicLinking.md
Without this, the memory and table areas allocated for it only have default alignment. Noticed this when improving the current emscripten dynamic library support.
=> Allow dynamic libraries to request a specific alignment for the memory and table 

Linking.md
The changes document new data structure needed relocations in the custom sections. It will be useful for debug section (DWARF) and, probably, for [annotations](https://github.com/WebAssembly/annotations).
Current prototypes:
- https://reviews.llvm.org/D44184
- https://reviews.llvm.org/D45118
- https://github.com/yurydelendik/wasm-dwarf
=> Enum value and structures for debug custom sections

ProducersSection.md
As discussed in #63.  Feedback and suggestions welcome.
In the "Known tools" lists, I intentionally included the bare-minimum which @dschuff and team can review.  After the initial PR merges, I'd expect Rust, Blazor, etc to file PRs, adding the tool names that make sense to them.
I think we should also introduce some custom .wat syntax for this custom section, but I'd like to see some agreement on the fundamental fields, as proposed in the binary format, before adding that, so I left this as TODO in this PR.
If anyone wants to implement a producer of this section, I'd be more than happy to validate the output in SpiderMonkey by implementing a consumer; just ping me.
=> Add initial ProducersSection.md

DynamicLinking.md
This comes from my work to teach Emscripten dynamic linker to support
library -> library linkage:
https://github.com/kripken/emscripten/pull/7512
The motivation is that without support for DSO -> DSO linking, it becomes
problematic in cases when there are several shared libraries that all
need to use another should-be shared functionality, while linking that
should-be shared functionality to main module is not an option for size
reasons. See above pull-request for more details.
In order to support library -> library linkages, we have to store
somewhere the information about which other libraries, a library needs.
This patch extends "dylink" section with such information, which is
similar to how ELF handles the same situation with DT_NEEDED entries.
/cc @sbc100
=> DynamicLinking: Extend "dylink" section with [] of needed libraries

BasicCABI.md
This begins documenting the C ABI. For now I've started with the format used by the x86-64 sysV ABI, but for now the format is less important since I want to get through as much as we can before the LLVM branch.
=> Fundamental scalar types

BasicCABI.md
This bit is taken directly from the SysV ABI, but I *believe* this is what Clang implements by default. Still looking but I'm posting this here in case someone knows better
=> C ABI aggregates and bitfields

Linking.md
This is an ABI break so bump the metadata version to 2
=> Store segment alignment as a power of 2, and bump metadata version to 2

Linking.md
Adds a new "target_features" custom section that lists the features an
object was built with. It is an error to link objects with mismatched
target feature sets.
The presence of the "atomics" feature also replaces the value of the
shared bit on object file memory import as the signal to the linker
that it should use shared memory. The target features section is more
generally useful and less hacky than the old solution.
=> Target features section

Linking.md
Remove the sentence about the linker producing shared memory if
`atomics` is present because the linker still requires the
--shared-memory flag to be passed in order to produce a shared memory.
=> Update target section, add `mutable-globals`

BasicCABI.md
Reflow text, add spacing to stack frame table, mention that higher addresses are on top.
(feedback from #87)
=> Improve readability of .md source

Linking.md
This adds documentation for the `WASM_SYM_EXPLICIT_NAME` flag, added in lld r353473, and LLVM r353474 and r353476.
In short, this accompanies the new import_name attribute, which allows symbols to be declared with a wasm import name that differs from the symbol name, like this:
```c
void foo(void) __attribute__((import_module("bar"), import_name("qux")));
```
This is useful because "bar" might be a wasm module that isn't necessarily written in C and does't follow C's norms for reserved identifiers, or defines names that otherwise conflict with the importing program's names.
=> Document the new WASM_SYM_EXPLICIT_NAME flag.

ProducersSection.md
While `Webpack` is not a SDK, it conforms with the description
> designates the top-level "thing" that the developer installs and interacts with directly to produce the wasm module
For ref https://github.com/webpack/webpack/issues/8429
`webassemblyjs` is the underlying tool that Webpack uses.
=> Add Webpack/webassemblyjs in producers

ProducersSection.md
As of version 0.1.5, `wasm-snip` will (optionally) add itself to the "processed-by" individual tools subsection of the "producers" custom section.
https://github.com/rustwasm/wasm-snip/commit/a1332a092811c7e882f9011bef0b515f8ff6c64d
=> Add wasm-snip to known individual tools

DynamicLinking.md
This change removes the `Planned Changes` section and makes this
the primary ABI.   The old ABI is mentioned only in reference to the
emscripten implementation.
=> Update DynamicLinking.md with current status

Linking.md
The reference types proposal adds support for multiple table indices,
requiring us to reason about tables in linking. To make sure the various
tools use consistent names/constants for the required new relocation
type, add it to the list here, giving it an authoritative number.
This is based on my WIP support for LLVM here:
https://reviews.llvm.org/D66035, but I figured it'd be good to get
this out of the way first, so we can simultaneously start adding
support to other tools and make sure everybody has consistent numbers.
=> Allocate magic constants for reference-types proposal

Linking.md
Reduces requirements for runtimes by changing `__wasm_init_memory` to
be the start function rather than being called from
`__wasm_call_ctors` or manually. Also adds language about
synchronization guarantees provided by `__wasm_init_memory`.
=> Update passive memory initialization scheme

Linking.md
Describes the roles played by the linker and compiler in using the
target feature section to disallow thread-unsafe linking.
Also updates the list of features and the section about the start
function to reflect the latest additions.
=> Describe MVP lowing of atomics and TLS

Linking.md
This adds documentation for the new `NO_STRIP` flag, allowing symbols to
be kept alive to support __attribute__((used)).
The `NO_STRIP` symbol flag is implemented in lld in
https://reviews.llvm.org/D62542 and in LLVM in
https://reviews.llvm.org/D66968.
=> Document `NO_STRIP`.

Linking.md
A user rolling their own toolchain was asking after their missing
constructors on llvm-dev, and I was going to point them to the
documentation of __wasm_call_ctors wehen I discovered that there was
none. This PR fixes that hole in our docs.
=> Document __wasm_call_ctors

BasicCABI.md
Change the ABI for the user entry point to rename `main` to
`__main_argc_argv` when it has argc/argv. This is needed because
wasm requires caller and callee signatures to match, so the
traditional trick of passing main arguments even if it doesn't
expect them doesn't work.
LLVM and related tools have been using the name `__original_main`
for a similar purpose, but that's a confusing name.
There's also a change here in that this is renaming the argc/argv
form rather than renaming the nullary form. The choice is somewhat
arbitrary, but I think it's slightly nicer to bias the aesthetics
toward the no-argument form, because that's the smaller and
simpler form.
=> Rename argc/argv `main` to `__main_argc_argv`

Linking.md
I think this is just a typo or left over from some old
convention?
=> R_WEBASSEMBLY_* => R_WASM_*

Debugging.md
=> Add Debugging.md

Debugging.md
A follow-up to #149. See #148.
=> Add a section on sourceMappingURL

BasicCABI.md
This matches the understanding found widely on the web, and the logic of the acronym.
It is also handy to have a type you know will be i32.
=> BasicCABI: LP64 means 32 bit int

BasicCABI.md
=> Document function signatures in C ABI

Linking.md
I've just finished updating a toy compiler to output object files instead of using the text format, so I thought it'd be good to include things that weren't clear to me from reading through the linking docs.
There are some details that I think would still be useful to include somewhere, although I'm not sure what the most appropriate place would be, nor am I sure whether there are alternative methods for the below. My impression, mostly from writing some C code and inspecting the resulting object file, is:
* rather than defining memory in the object file, memory should be imported from `env.__linear_memory`
* rather than defining a function table, one should be imported from `env.__indirect_function_table`
* on recent (>= 12) versions of LLVM, if `__wasm_call_ctors` is not called, then …
=> Update linking docs

DynamicLinking.md
llvm change: https://reviews.llvm.org/D109595                                                
binaryen change: https://github.com/WebAssembly/binaryen/pull/4141          
wabt change:  https://github.com/WebAssembly/wabt/pull/1707                 
emscripten change: https://github.com/emscripten-core/emscripten/pull/15019
=> DynamicLinking: Specify new "dylink.0" section format

Signatures.md
Add `Signatures.md`, describing a signature format for WebAssembly modules.
This is a work in progress, and the format is still subject to change. 
The `Signatures.md` file here will be kept up to date as changes are being made, but we still need a place for discussions and reference implementations.
Signatures for WebAssembly modules are currently being discussed here: https://github.com/wasm-signatures/design
Would it make sense to move that design/discussion repository to the WebAssembly organization?
=> Signatures.md: digital signatures for WebAssembly modules

DynamicLinking.md
Emscripten no longer has to rewrite LLVM's output for dynamic libraries.
=> Remove obsolete paragraph about dynamic linking

Linking.md
Consolidate the section describing TLS emulation within MVP WebAssembly with the rest of threading support.
Closes #184
=> Linking.md: consolidate threading sections

CodeMetadata.md
Change size from a fixed value of 0x4 to a variable unsigned integer.
=> Fix CodeMetadata encoding definition for trace_inst

Linking.md
=> Add limitations section to Linking.md to clarify element and data segment indices renumbering is not supported (#193)

Coredump.md
Closes https://github.com/WebAssembly/tool-conventions/issues/190.
Adapted from https://github.com/xtuc/wasm-coredump-format. I suggest we start with my initial idea and iterate on the design, does that make sense? I'm planning to send followup changes to address points we discussed during the CG.
=> Add initial coredump document

Coredump.md
This change adds typing to local and stack values. Technically the type
isn't strictly necessary as DWARF should indicate how to interpret the values.
However, using types allows us to represent the lack of value, because
it has been optimized out and more complex values like reference types.
Closes https://github.com/WebAssembly/tool-conventions/issues/198
=> Coredump: add local/stack value typing

ProducersSection.md
[Javy](https://github.com/Shopify/javy) is a tool that takes JavaScript source code as input and outputs a WebAssembly module that executes that code.
=> Add JavaScript and Javy as known names in producers

Coredump.md
This change adds a `funcidx` value in each stack frame. Allowing the `codeoffset` to be left empty, if unknown or not accurate.
Another benefit is that debugging a coredump without DWARF is still able to display a backtrace of func indices.
=> coredump: add funcidx to stack frames

BuildId.md
Describe the `build_id` custom section and its use cases.
=> Add a document for build IDs

BasicCABI.md
=> Clarify that small scalars are extended before passing or returning

Linking.md
The documentation for the `WASM_SEGMENT_INFO` subsection includes a `flags` field, but I didn't see any mention of the flags themselves, yet I found a STRINGS flags being encoded and decoded in practice by both clang and wasm-objdump.
It looks like these are the definitions of these in the header files [wabt/common.h](https://github.com/WebAssembly/wabt/blob/e97a1cbe920b96174c59ee347969eaf42d4116f0/include/wabt/common.h#L334-L335) and [llvm/BinaryFormat/Wasm.h](https://github.com/llvm/llvm-project/blob/142e567cf00815f7d1b3d72aaf298212a3f83ab2/llvm/include/llvm/BinaryFormat/Wasm.h#L392-L395)
I have just listed these flag names along with their values for now, since I didn't want to lead the reader astray by making assumptions about how these flags are used during linking.  Feel free to add …
=> Linking: Add the missing list of segment flags

Signatures.md
In order to avoid probing signatures that don't match a public key, signatures are prefixed with an algorithm identifier.
That identifier was present in examples, but not in the specification.
So, mention it in the specification.
In addition, current implementations don't consider that the identifier is part of the signature, so match these implementations. It doesn't make any difference beyond the encoded signature length.
=> Signatures.md: update and document the signature identifier

DynamicLinking.md, Linking.md
=> Add missing relocations and segment flags to the documentation.

DynamicLinking.md, ProducersSection.md
This proposes a text format based on the annotations proposal for two custom sections defined in this repository. The annotations proposal is likely to reach phase 4 and "basically done" status in the near future. The [wasm-tools repository][tools] has implemented the text format documented here for a bit now and it seemed best to document this upstream as well to both gather consensus and help guide other implementations.
[tools]: https://github.com/bytecodealliance/wasm-tools
I'll note that the text format documented here is the first thing I thought of for these sections. Right now these are largely used in read-only capacities where it's helpful for inspecting output but I'm not aware of anyone relying on the exact syntax. In that sense I'm more than happy to change syntax here and …
=> Add a text format for `producers` and `dylink.0` custom sections

Linking.md
=> Add subsection headers to linking section

BasicModuleABI.md, ToolchainIndependentABI.md
The Wasm ecosystem is currently not consistent in how "constructors" such as C++ static initializers and similar features in other languages are implemented, and the result is users reporting constructs running multiple times, and other users reporting constructors not getting run when they should.
WASI has [defined a convention] using an exported function named `_initialize`, however not all users are using WASI conventions. In particular, users of what is sometimes called "wasm32-unknown-unknown" are not expecting to follow WASI conventions. However, they still have a need for constructors working in a reliable way.
To address this, I propose moving this out of WASI and defining this as a toolchain-independent ABI, here in tool-conventions. This would recognize the `_initialize` …
=> Add a toolchain-independent ABI document, and propose `_initialize`

Linking.md
This has not been emitted in LLVM since
https://github.com/llvm/llvm-project/commit/3f34e1b883351c7d98426b084386a7aa762aa366.
=> [Linking] Remove 'Required' (0x3d) prefix from features section

Lime.md, Trail.md
I propose a new target CPU configuration for LLVM, and any toolchain or engine that wishes to share it, named "trail1".
Trail1 would enable mutable-globals, bulk-memory-opt*, multivalue, sign-ext, nontrapping-fptoint, extended-const, and call-indirect-overlong**. The specific set is open to debate here. The idea is, once we stabilize it, Trail1 would be stable and we would not add or remove features from that point on. Trail1 could be followed by Trail2 and so on in the future if we wish to add or remove features after that. And we can always define new non-Trail CPUs as well, if there are needs for different sets.
\* bulk-memory-opt would be a new feature that just includes `memory.copy` and `memory.fill`, and not the rest of bulk-memory
\*\* call-indirect-overlong would be a new feature …
=> Propose a new LLVM CPU configuration: Lime1

BasicCABI.md
Document the C ABI for `_BitInt`, `_Complex`, `__int128_t`, and `__uint128_t`. These follow the ABI currently used by clang, to the best of my knowledge.
Fixes #239.
=> Document the C ABI for `_BitInt` and other types.

DynamicLinking.md
Changes to the conventions for https://github.com/WebAssembly/tool-conventions/issues/244. 
cc @ryanking13 @sbc100.
=> Add runtime-path to DynamicLinking.md

DynamicLinking.md
This is my attempt to capture the discussion in
https://github.com/WebAssembly/tool-conventions/issues/232
=> DynamicLinking.md: add notes about memory/table exports

CodeMetadata.md
"\0" and "\1" there are meant to indicate bytes, but two characters are needed for that text encoding (for a whole byte).
This makes the example match the BranchHinting example:
https://github.com/WebAssembly/branch-hinting/blob/main/proposals/branch-hinting/Overview.md
and also makes them parse properly in the spec interpreter and Binaryen.
=> Fix CodeMetadata.md example annotations
